required = ["github.com/labstack/echo"]

[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.3.5"

[[constraint]]
  name = "upper.io/db.v3"
  version = "3.3.0"

  [[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.3"
[[constraint]]
  branch = "master"
  name = "github.com/MarcusMann/pongor-echo"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"
